from laboratories.libraries import maths_thinks as crypto

if __name__ == '__main__':
    crypto.separate()
    crypto.separate()
    print("НАЧАЛО ЛАБОРАТОРНОЙ РАБОТЫ: ")
    crypto.separate()
    print("Задание 1, находим шифротекст Y имея исходный текст X, открытый ключ e, и модуль шифрования N: ")
    crypto.encryption(17, 1_739, x=132, key="task_1")  # e, N, x
    crypto.separate()
    crypto.separate()
    print("Задание 2, находим значение исходного текста X, имея модуль шифрования N, открытый ключ е, и  Y : ")
    crypto.re_encryption_or_krmd(y_0=66, e=283, N=377)
    crypto.separate()
    crypto.re_encryption(y=66, e=283, N=377)
    crypto.separate()
    crypto.separate()
    print("Задание 3, находим значение  d, имея  N, открытый ключ е (метод факторизации ферма): ")
    closed_key = crypto.find_keys_ferma(e=519, N=4_183)
    crypto.separate()
    print("Задание 4, находим значение  X, имея  N, открытый ключ е и шифротекст Y : ")
    print("Метод перешифрования: ", )
    crypto.re_encryption_or_krmd(y_0=13, e=7, N=143)  # y, e, N
    crypto.separate()
    crypto.re_encryption(y=13, e=7, N=143)
    crypto.separate()
    crypto.separate()
    print("Задание 5, найти методом бесключевого чтения исходный текст X, имея е1, е2, N и шифротексты Y1,Y2: ")
    crypto.keyless_reading(y1=1_682, y2=42, e1=7, e2=3, N=3_403)
    crypto.re_encryption(y=42, e=3, N=3_403)
    crypto.separate()
    crypto.separate()
    print("НАЧАЛО ТЕСТОВ:")
    crypto.separate()
    crypto.separate()
    test = crypto.encryption(1_874_947_153_801, 2_797_477_623_911, x=543, key="automate")  # p, q, x
    y_auto, e1_auto, d1_auto, e2_auto, N_auto = test
    crypto.decryption(y_auto, d1_auto, N_auto)
    crypto.separate()
    crypto.re_encryption(y_auto, e1_auto, N_auto)
    print("Дешифруем, и делаем вывод, что при перешифровании(x += 1) сложность дешифровки зависит от длины X")
    crypto.separate()
    print("Задаем псевдогенератором случайные простые p и q, и автоматически генерируем ключ e:")
    p_and_q = crypto.generate_simple_number_p_q(20, 20)  # p, q
    rand_cypher_e_d = crypto.encryption(p_and_q[0], p_and_q[1], x=42_344_411, key="rand")
    y1_test, e1_test, d1_test, e2_test, y2_test, N_test = rand_cypher_e_d
    crypto.decryption(y1_test, d1_test, N_test)
    crypto.separate()
    crypto.keyless_reading(y1_test, y2_test, e1_test, e2_test, N_test)
    crypto.separate()
    exit()
